[toolchain]
package_manager = "yarn"
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
onyx_protocol = "FjMdzw1x2zobB9UD8pcezbmzLwuHQnKMzit68Zbx87PG"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
